name: "Download SDL2"
description: "Download SDL2 sources for Windows, using MSVC."

branding:
  icon: "download"
  color: "green"

inputs:
  version:
    description: "The version of SDL2 that will be downloaded"
    required: true

  destination:
    description: "Where the SDL2 sources will be saved"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download sources
      run: Invoke-WebRequest -Uri "https://libsdl.org/release/SDL2-devel-${{inputs.version}}-VC.zip" -OutFile ${{inputs.destination}}/SDL2-devel-${{inputs.version}}-VC.zip
      shell: powershell

    - name: Unzip sources
      run: |
        cd ${{inputs.destination}}
        7z x -y SDL2-devel-${{inputs.version}}-VC.zip
        del SDL2-devel-${{inputs.version}}-VC.zip
      shell: cmd
