name: "Download SDL2"
description: "Download SDL2 sources and binaries for Windows, using MSVC."

branding:
  icon: "download"
  color: "green"

inputs:
  version:
    description: "The version of SDL2 that will be downloaded"
    required: true
    default: 2.0.14

  sources_destination:
    description: "Where the SDL2 sources will be saved"
    required: true

  binaries_destination:
    description: "Where the SDL2 runtime binaries will be saved"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download sources
      run: Invoke-WebRequest -Uri "https://libsdl.org/release/SDL2-devel-${{inputs.version}}-VC.zip" -OutFile ${{inputs.sources_destination}}/SDL2-devel-${{inputs.version}}-VC.zip
      shell: powershell

    - name: Unzip sources
      run: |
        cd ${{inputs.sources_destination}}
        7z x -y SDL2-devel-${{inputs.version}}-VC.zip
        del SDL2-devel-${{inputs.version}}-VC.zip
      shell: cmd

    - name: Download runtime binaries
      run: Invoke-WebRequest -Uri "https://www.libsdl.org/release/SDL2-${{inputs.version}}-win32-x64.zip" -OutFile ${{inputs.binaries_destination}}/SDL2-${{inputs.version}}-win32-x64.zip
      shell: powershell

    - name: Unzip runtime binaries archive
      run: |
        cd ${{inputs.binaries_destination}}
        7z x -y SDL2-${{inputs.version}}-win32-x64.zip
        del SDL2-${{inputs.version}}-win32-x64.zip
      shell: cmd
